/**
 * Every event emitted by the Overlive SDK conforms to this shape.
 * Platform adapters are responsible for normalizing their raw payloads
 * into these types before emitting to the bus.
 */

// ─── Platform identifiers ────────────────────────────────────────────────────

export type Platform = 'twitch' | 'streamelements' | 'kick' | 'youtube' | (string & {})

// ─── Currency discriminator (used in RedemptionEvent) ────────────────────────

export type RedemptionCurrency =
  | {
      kind: 'bits'
      /** Number of bits cheered */
      amount: number
    }
  | {
      kind: 'channel_points'
      /** Number of channel points spent */
      amount: number
      /** The reward title as configured by the broadcaster */
      rewardTitle: string
      /** The reward id as configured by the broadcaster */
      rewardId: string
      /** Whether the redemption requires broadcaster approval */
      requiresApproval: boolean
    }
  | {
      kind: 'tip'
      /** Tip amount in the sender's currency */
      amount: number
      /** ISO 4217 currency code e.g. "USD", "EUR" */
      currency: string
      /** Amount formatted with symbol, e.g. "$5.00" */
      formattedAmount: string
    }
  | {
      kind: 'superchat'
      amount: number
      currency: string
      formattedAmount: string
      /** YouTube superchat colour tier */
      colorTier?: string
    }

// ─── Subscription tiers ──────────────────────────────────────────────────────

export type SubscriptionTier = 'tier1' | 'tier2' | 'tier3' | 'prime' | 'unknown'

// ─── Emote (resolved or unresolved) ─────────────────────────────────────────

export type EmotePlatform = 'twitch' | '7tv' | 'bttv' | 'ffz'

export interface ResolvedEmote {
  id: string
  name: string
  platform: EmotePlatform
  urls: {
    x1: string
    x2: string
    x4: string
  }
  /** True if the emote is animated (GIF / WEBP) */
  animated: boolean
}

// ─── Chat message tokens ─────────────────────────────────────────────────────

export type MessageToken =
  | { type: 'text'; value: string }
  | { type: 'emote'; emote: ResolvedEmote }
  | { type: 'mention'; username: string }
  | { type: 'url'; href: string; display: string }
  | { type: 'cheer'; amount: number }

// ─── Base event shape ────────────────────────────────────────────────────────

export interface BaseEvent {
  /** Unique event id (generated by the SDK if not provided by the platform) */
  id: string
  /** Which platform this event originated from */
  platform: Platform
  /**
   * The registry instance id of the adapter that emitted this event.
   * Stamped by the SDK when the adapter dispatches — consumers do not set it.
   * Lets consumers route events when multiple adapters of the same platform
   * are registered (e.g. several Twitch accounts).
   */
  sourceInstanceId: string
  /**
   * The human-readable channel/broadcaster login or slug (lowercase).
   * On Twitch this is the broadcaster login (e.g. "twitchplays").
   * On platforms with no login concept (e.g. StreamElements), this falls
   * back to the platform-native channel id.
   */
  channel: string
  /**
   * The platform-native channel identifier (e.g. Twitch broadcaster_user_id).
   * Present when the platform exposes a stable numeric/opaque id distinct
   * from the human-readable `channel`. Absent for platforms where the two
   * are the same.
   */
  channelId?: string
  /** Wall-clock time the event occurred (or was received if unknown) */
  timestamp: Date
  /**
   * The original unmodified payload from the platform.
   * Useful for accessing fields not yet mapped by the adapter.
   */
  raw: unknown
  /**
   * Whether this event was deduplicated — i.e. an equivalent event arrived
   * from another adapter but was suppressed. The surviving event carries
   * this flag as false; suppressed ones are never emitted.
   */
  deduplicated?: false
}

// ─── Concrete event types ─────────────────────────────────────────────────────

/**
 * Someone spent something — bits, channel points, a tip, or a superchat.
 * The `currency` discriminator tells you exactly what kind.
 */
export interface RedemptionEvent extends BaseEvent {
  type: 'redemption'
  data: {
    username: string
    displayName: string
    userId?: string
    currency: RedemptionCurrency
    /** Optional message attached to the redemption */
    message?: string
  }
}

export interface SubscriptionEvent extends BaseEvent {
  type: 'subscription'
  data: {
    username: string
    displayName: string
    userId?: string
    tier: SubscriptionTier
    /** Total cumulative months subscribed */
    months: number
    /** Streak of consecutive months (if shared) */
    streak?: number
    /** Whether this is the user's first ever sub to this channel */
    isFirst: boolean
    /** Whether this is a resub */
    isResub: boolean
    /** Whether this sub was gifted */
    isGift: boolean
    /** If gifted, who gifted it */
    gifter?: {
      username: string
      displayName: string
      userId?: string
    }
    /** Resub message */
    message?: string
  }
}

/** Bulk gift sub event — one gifter, many recipients */
export interface GiftBombEvent extends BaseEvent {
  type: 'gift_bomb'
  data: {
    gifter: {
      username: string
      displayName: string
      userId?: string
    }
    /** Number of subs gifted in this bomb */
    count: number
    tier: SubscriptionTier
    /** Total gifts this gifter has given to the channel (if known) */
    totalGifts?: number
    /** Whether the gifter was anonymous */
    anonymous: boolean
  }
}

export interface RaidEvent extends BaseEvent {
  type: 'raid'
  data: {
    /** The raiding channel */
    from: {
      username: string
      displayName: string
      userId?: string
    }
    /** Number of viewers in the raid */
    viewerCount: number
  }
}

export interface FollowEvent extends BaseEvent {
  type: 'follow'
  data: {
    username: string
    displayName: string
    userId?: string
  }
}

export interface ChatMessageEvent extends BaseEvent {
  type: 'chat.message'
  data: {
    messageId: string
    username: string
    displayName: string
    userId?: string
    /** Raw message text */
    text: string
    /**
     * Parsed tokens — only present if subscriber requested emote resolution
     * via { resolveEmotes: true } in the subscription options.
     */
    tokens?: MessageToken[]
    color?: string
    badges: Array<{ id: string; version: string }>
    /** True if the user is a moderator */
    isMod: boolean
    /** True if the user is a subscriber */
    isSub: boolean
    /** True if the user is the broadcaster */
    isBroadcaster: boolean
    /** True if this is a /me action message */
    isAction: boolean
    /** True if the message was sent with a highlight (channel points) */
    isHighlighted: boolean
    /** Bits cheered inline in the message, if any */
    cheerAmount?: number
  }
}

export interface ChatCommandEvent extends BaseEvent {
  type: 'chat.command'
  data: {
    messageId: string
    username: string
    displayName: string
    userId?: string
    /** Command name without the prefix, e.g. "points" for "!points" */
    command: string
    /** The prefix used, defaults to "!" */
    prefix: string
    /** Arguments after the command */
    args: string[]
    /** Full raw message text */
    text: string
    color?: string
    badges: Array<{ id: string; version: string }>
    isMod: boolean
    isSub: boolean
    isBroadcaster: boolean
  }
}

export interface AdStartEvent extends BaseEvent {
  type: 'ad.start'
  data: {
    /** Duration of the ad break in seconds */
    durationSeconds: number
    /** Whether the ad was triggered automatically */
    isAutomatic: boolean
  }
}

export interface AdEndEvent extends BaseEvent {
  type: 'ad.end'
  data: {
    /** How long the ad break actually ran in seconds */
    durationSeconds: number
  }
}

export interface BanEvent extends BaseEvent {
  type: 'ban'
  data: {
    username: string
    displayName: string
    userId?: string
    /** Moderator who issued the ban */
    moderator?: {
      username: string
      userId?: string
    }
    /** Reason provided, if any */
    reason?: string
    /** If present, this is a timeout — duration in seconds */
    timeoutSeconds?: number
    /** True if this is a permanent ban */
    isPermanent: boolean
  }
}

export interface DeleteMessageEvent extends BaseEvent {
  type: 'chat.delete'
  data: {
    messageId: string
    username: string
    userId?: string
    /** The deleted message text (if available) */
    text?: string
    /** Moderator who deleted the message */
    moderator?: {
      username: string
      userId?: string
    }
  }
}

export interface StreamOnlineEvent extends BaseEvent {
  type: 'stream.online'
  data: {
    title: string
    category?: string
    language?: string
  }
}

export interface StreamOfflineEvent extends BaseEvent {
  type: 'stream.offline'
  data: Record<string, never>
}

// ─── Union of all events ──────────────────────────────────────────────────────

export type OverliveEvent =
  | RedemptionEvent
  | SubscriptionEvent
  | GiftBombEvent
  | RaidEvent
  | FollowEvent
  | ChatMessageEvent
  | ChatCommandEvent
  | AdStartEvent
  | AdEndEvent
  | BanEvent
  | DeleteMessageEvent
  | StreamOnlineEvent
  | StreamOfflineEvent

export type EventType = OverliveEvent['type']

/** Extract the event object for a given type string */
export type EventByType<T extends EventType> = Extract<OverliveEvent, { type: T }>

/**
 * Event shape as produced by adapter normalizers, before the core stamps
 * `sourceInstanceId`. Adapters never need to know their own instance id —
 * the SDK injects it as events flow through the kit.
 */
export type AdapterEmittedEvent =
  | Omit<RedemptionEvent,        'sourceInstanceId'>
  | Omit<SubscriptionEvent,      'sourceInstanceId'>
  | Omit<GiftBombEvent,          'sourceInstanceId'>
  | Omit<RaidEvent,              'sourceInstanceId'>
  | Omit<FollowEvent,            'sourceInstanceId'>
  | Omit<ChatMessageEvent,       'sourceInstanceId'>
  | Omit<ChatCommandEvent,       'sourceInstanceId'>
  | Omit<AdStartEvent,           'sourceInstanceId'>
  | Omit<AdEndEvent,             'sourceInstanceId'>
  | Omit<BanEvent,               'sourceInstanceId'>
  | Omit<DeleteMessageEvent,     'sourceInstanceId'>
  | Omit<StreamOnlineEvent,      'sourceInstanceId'>
  | Omit<StreamOfflineEvent,     'sourceInstanceId'>
